<a href="https://colab.research.google.com/github/rickiepark/MLQandAI/blob/main/supplementary/q10-random-sources/data-sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 샘플링과 셔플링

### 랜덤 시드 없이 데이터 분할하기

In [ ]:
import numpy as np

x_toydata = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9.])
y_labels = np.array([ 0,  1,  0,  1, 1,  0,  0,  1,  0 ])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x_toydata, y_labels, test_size=0.3, shuffle=True, stratify=y_labels
)

print("X_train", X_train)
print("X_test", X_test)

X_train [6. 9. 8. 5. 7. 2.]
X_test [3. 1. 4.]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x_toydata, y_labels, test_size=0.3, shuffle=True, stratify=y_labels
)

print("X_train", X_train)
print("X_test", X_test)

X_train [3. 7. 4. 2. 5. 1.]
X_test [8. 9. 6.]


### 랜덤 시드를 사용해 데이터 분할하기

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x_toydata, y_labels, test_size=0.3, shuffle=True, stratify=y_labels,
    random_state=123
)

print("X_train", X_train)
print("X_test", X_test)

X_train [9. 2. 8. 3. 5. 7.]
X_test [4. 1. 6.]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x_toydata, y_labels, test_size=0.3, shuffle=True, stratify=y_labels,
    random_state=123
)

print("X_train", X_train)
print("X_test", X_test)

X_train [9. 2. 8. 3. 5. 7.]
X_test [4. 1. 6.]


### 랜덤 시드 없이 K-폴드 분할하기

In [ ]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=3, shuffle=True)

for train_idx, valid_idx in cv.split(x_toydata, y_labels):
    print("특성 값", x_toydata[train_idx])

특성 값 [1. 3. 4. 5. 7. 8.]
특성 값 [2. 3. 4. 5. 6. 9.]
특성 값 [1. 2. 6. 7. 8. 9.]


In [ ]:
for train_idx, valid_idx in cv.split(x_toydata, y_labels):
    print("특성 값", x_toydata[train_idx])

특성 값 [2. 3. 5. 6. 8. 9.]
특성 값 [1. 2. 3. 4. 7. 8.]
특성 값 [1. 4. 5. 6. 7. 9.]


### 랜덤 시드를 사용해 K-폴드 분할하기

In [ ]:
cv = StratifiedKFold(n_splits=3, random_state=123, shuffle=True)

for train_idx, valid_idx in cv.split(x_toydata, y_labels):
    print("특성 값", x_toydata[train_idx])

특성 값 [3. 4. 5. 6. 8. 9.]
특성 값 [1. 2. 4. 5. 6. 7.]
특성 값 [1. 2. 3. 7. 8. 9.]


In [ ]:
cv = StratifiedKFold(n_splits=3, random_state=123, shuffle=True)

for train_idx, valid_idx in cv.split(x_toydata, y_labels):
    print("특성 값", x_toydata[train_idx])

특성 값 [3. 4. 5. 6. 8. 9.]
특성 값 [1. 2. 4. 5. 6. 7.]
특성 값 [1. 2. 3. 7. 8. 9.]


## 랜덤 시드 없이 데이터셋 로드하기

In [ ]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader


train_dataset = datasets.MNIST(root='./data', train=True,
                               transform=transforms.ToTensor(), download=True)
train_loader = DataLoader(dataset=train_dataset, batch_size=8, shuffle=True)

for inputs, labels in train_loader:
    pass
print(labels)

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 9.91M/9.91M [00:00<00:00, 35.7MB/s]


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 28.9k/28.9k [00:00<00:00, 1.12MB/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 1.65M/1.65M [00:00<00:00, 9.48MB/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 4.54k/4.54k [00:00<00:00, 4.87MB/s]


Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw

tensor([2, 3, 4, 5, 7, 0, 2, 4])


In [ ]:
train_loader = DataLoader(dataset=train_dataset, batch_size=8, shuffle=True)

for inputs, labels in train_loader:
    pass
print(labels)

tensor([0, 1, 0, 8, 0, 9, 8, 6])


## 랜덤 시드를 사용해 데이터셋 로드하기

In [ ]:
import torch

torch.manual_seed(123)
train_loader = DataLoader(dataset=train_dataset, batch_size=8, shuffle=True)

for inputs, labels in train_loader:
    pass
print(labels)

tensor([1, 8, 8, 7, 2, 5, 4, 1])


In [ ]:
torch.manual_seed(123)
train_loader = DataLoader(dataset=train_dataset, batch_size=8, shuffle=True)

for inputs, labels in train_loader:
    pass
print(labels)

tensor([1, 8, 8, 7, 2, 5, 4, 1])
