<a href="https://colab.research.google.com/github/rickiepark/MLQandAI/blob/main/supplementary/q10-random-sources/random-weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 랜덤한 가중치 초기화

### 랜덤 시드 사용하지 않는 경우

In [ ]:
import torch


layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[ 0.3208, -0.4872],
        [-0.5012, -0.4676],
        [-0.4645, -0.3802]], requires_grad=True)


In [ ]:
layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[ 0.3519,  0.1797],
        [ 0.3982, -0.0328],
        [-0.5613,  0.1462]], requires_grad=True)


### 랜덤 시드 사용하는 경우

In [ ]:
torch.manual_seed(123)

layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[-0.2883,  0.0234],
        [-0.3512,  0.2667],
        [-0.6025,  0.5183]], requires_grad=True)


In [ ]:
torch.manual_seed(123)

layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[-0.2883,  0.0234],
        [-0.3512,  0.2667],
        [-0.6025,  0.5183]], requires_grad=True)
